#include "motor.h"

void rear (uint8_t v) { //acionar somente um timer por lado
	GPIO_D->DDR = SET(PD6); //OC0A, OC2A
	GPIO_B->DDR = SET(PB3);

	TIMER_0->TCCRA = SET(WGM01) | SET(WGM00) | SET(COM0A1);
	TIMER_0->TCCRB = SET(CS00) | SET(CS01); //PRESCALLER DE 64
	TIMER_0->OCRA = v;

	TIMER_2->TCCRA = SET(WGM21) | SET(WGM20) | SET(COM2A1);
	TIMER_2->TCCRB = SET(CS22); //PRESCALLER DE 64
	TIMER_2->OCRA = v;
}

void front (uint8_t v) {
	GPIO_D->DDR = SET(PD5) | SET(PD3); //OC0B, OC2B

	TIMER_0->TCCRA = SET(WGM01) | SET(WGM00) | SET(COM0B1);
	TIMER_0->TCCRB = SET(CS00) | SET(CS01); //PRESCALLER DE 64 É PARA OS DOIS
	TIMER_0->OCRB = v;

	TIMER_2->TCCRA = SET(WGM21) | SET(WGM20) | SET(COM2B1);
	TIMER_2->TCCRB = SET(CS22); //PRESCALLER DE 64 É PARA OS DOIS
	TIMER_2->OCRB = v;
}

void right (uint8_t v) {

	GPIO_D->DDR = SET(PD3); // OC2B

	TIMER_0->TCCRA = SET(WGM01) | SET(WGM02);

	TIMER_2->TCCRA = SET(WGM21) | SET(WGM20) | SET(COM2B1);
	TIMER_2->TCCRB = SET(CS22); //PRESCALLER DE 64 É PARA OS DOIS
	TIMER_2->OCRB = v;

}

void left (uint8_t v){
	GPIO_D->DDR = SET(PD5); // OC0B

	TIMER_0->TCCRA = SET(WGM01) | SET(WGM00) | SET(COM0B1);
	TIMER_0->TCCRB = SET(CS00) | SET(CS01); //PRESCALLER DE 64 É PARA OS DOIS
	TIMER_0->OCRB = v;

	TIMER_2->TCCRA = SET(WGM21) | SET(WGM22); //(reservado)
}

void tank (uint8_t v1, uint8_t v2) {
	GPIO_D->DDR = SET(PD6) | SET(PD3); // OC0A e OC2B

	TIMER_0->TCCRA = SET(WGM01) | SET(WGM00) | SET(COM0A1);
	TIMER_0->TCCRB = SET(CS00) | SET(CS01); //PRESCALLER DE 64 É PARA OS DOIS
	TIMER_0->OCRA = v1;

	TIMER_2->TCCRA = SET(WGM21) | SET(WGM20) | SET(COM2B1);
	TIMER_2->TCCRB = SET(CS22); //PRESCALLER DE 64 É PARA OS DOIS
	TIMER_2->OCRB = v2;
}

void test (uint8_t v1, uint8_t v2) {
	GPIO_D->DDR = SET(PD6) | SET(PD5); // OC0A e OC2B

	TIMER_0->TCCRA = SET(WGM01) | SET(WGM00) | SET(COM0A1) | SET(COM0B1);
	TIMER_0->TCCRB = SET(CS00) | SET(CS01); //PRESCALLER DE 64 É PARA OS DOIS
	TIMER_0->OCRA = v1;
	TIMER_0->OCRB = v2;
}
